import './globals.css'
import { Josefin_Sans } from 'next/font/google'

const josef = Josefin_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'I love U',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${josef.className}`}>
        {children}
      </body>
    </html>
  )
}
