import './globals.css'
import { Josefin_Sans } from 'next/font/google'

const josef = Josefin_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'I love U',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${josef.className}`}>


        <nav className='fixed flex z-10 w-full h-[55px] bg-gradient-to-r from-orange-600 from-10% via-orange-300 via-30% to-amber-300 to-70% items-center justify-around mobile-s:h-14 mobile-s:w-full'>

          <div className='flex px-8 gap-5 mobile-s:px-2 mobile-s:gap-2 mobile-s:text-xs mobile-s:text-center'>

            <span>
              I love you 💞
            </span>

            <span>
              You are my sunshine 🎀
            </span>

            <span>
              You complete me ✨
            </span>

            <span className='mobile-s:hidden'>
              You are my everything 🎇
            </span>

            <span className='mobile-s:hidden'>
              I'm grateful for you 💝
            </span>

            <span className='mobile-s:hidden'>
              You're my dream come true 🌷
            </span>

            <span className='mobile-s:hidden'>
              You mean the world to me 💐
            </span>

          </div>

        </nav>

        <footer></footer>


        {children}
      </body>
    </html>
  )
}
